sudo: required
dist: bionic

install:
        - bash -xve ./test/travis_ros_install.bash
        - source ~/catkin_ws/devel/setup.bash
before_script:
        - bash -xve ./test/travis_package_make.bash
        - source ~/catkin_ws/devel/setup.bash
        - bash -xve ./test/travis_prepare_dummy_files.bash
script:
        - cd /home/travis/.ros/
        - ls
          #- rostest pimouse_ros test.launch
