sudo: required
dist: bionic

env:
        - ROS_LOG_DIR=/home/travis/.ros/log

install:
        - bash -xve ./test/travis_ros_install.bash
        - source ~/catkin_ws/devel/setup.bash
before_script:
        - bash -xve ./test/travis_package_make.bash
        - source ~/catkin_ws/devel/setup.bash
        - bash -xve ./test/travis_prepare_dummy_files.bash
script:
        #- cd /home/travis/.ros/
        #- sudo mkdir test_results
        #- cd test_results
        #- sudo mkdir pimouse_ros
        #- cd ~/catkin_ws/src/pimouse_ros/
        - sudo chmod 666 /home/travis/.ros/
        - rostest pimouse_ros test.launch
