sudo: required
dist: bionic

script:
        - bash -xve ./test/travis_ros_install.bash
        - source ~/catkin_ws/devel/setup.bash
        - bash -xve ./catkin_ws/src/pimouse_ros/test/travis_package_make.bash
        - source ~/catkin_ws/devel/setup.bash
        - bash -xve ./test/travis_prepare_dummy_files.bash
        - rostest ./pimouse_ros/launch/test.launch
